name: techquiz
on:
  pull_request:
    branches:
      - Develop
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
      - name: Install Build
        run: npm run render-build
      - name: Test
        run: npm run test
